window.translations = {
  ru: {
    meta:{name:'Русский',choose:'ВЫБЕРИТЕ ЯЗЫК',switch:'Язык',brand:'ЧАС ПИК'},
    signature:'С любовью и лёгкой травмой от запары, Алина',
    hero:{duration:'Гайд на 3 минуты',kicker:'КОРОТКИЙ ГАЙД ДЛЯ КОМАНДЫ',peak:'ЧАС',hours:'ПИК.',intro:'Пара секунд сейчас может сэкономить несколько минут у чекера.',rule:'ОБЛЕГЧИ РАБОТУ ТОМУ, КТО ИДЁТ СЛЕДОМ.',start:'Открыть короткий гайд'},
    introduction:{heading:'В ЧАС ПИК БАРДАК НАЧИНАЕТСЯ БЫСТРО.',p1:'Когда готовы десятки заказов, а у чекера очередь курьеров, мелочи начинают сильно влиять на работу.',p2:'Здесь несколько простых правил, с которыми заказы легче упаковывать, находить и выдавать.',p3:'На каждое уходит пара секунд. Потом они экономят всей команде гораздо больше времени.',goalLabel:'ЦЕЛЬ ПРОСТАЯ:',goal:'ОБЛЕГЧИ РАБОТУ ТОМУ, КТО ИДЁТ СЛЕДОМ.'},
    labels:{before:'ДО',after:'ПОСЛЕ',wrong:'× НЕПРАВИЛЬНО',right:'✓ ПРАВИЛЬНО'},
    photos:{folded:'Боковая сторона пакета всё ещё сложена.',flat:'Боковая сторона пакета раскрыта и выровнена.',separate:'Пакеты одного заказа стоят в разных местах.',together:'Все пакеты каждого заказа стоят вместе.',finishedCarts:'Готовые заказы остались на тележках у чекера.',carts:'Пустые тележки загородили чекер.',waterLoose:'Упаковка воды стоит отдельно от пакетов заказа.',waterBag:'Упаковка воды лежит внутри пакета Wolt.',numberStyles:'Примеры разных, но разборчивых вариантов написания цифр.',handwriting939:'Настоящая наклейка на пакете с номером заказа 939, написанным от руки.'},
    sections:{
      ready:{step:'01 / ГОТОВО ЗНАЧИТ ГОТОВО',title:'Если заказ здесь, он готов.',equation:'ЗОНА УПАКОВКИ = МОЖНО УПАКОВЫВАТЬ',cart:'ТЕЛЕЖКА',area:'ЗОНА УПАКОВКИ',ready:'МОЖНО УПАКОВЫВАТЬ',notReady:'ЕЩЁ НЕ ГОТОВО',flowLabel:'Тележка едет в зону упаковки, когда заказ полностью готов',lead:'Упаковщик должен сразу начать работу.',noteTitle:'Чего-то не хватает?',note:'Скажи упаковщику и оставь тележку за пределами зоны упаковки, пока заказ не будет готов. Не добавляй товары после начала упаковки.'},
      number:{step:'02 / ПРОВЕРЬ НОМЕР',title:'Посмотри. Потом ещё раз.',lead:'Проверь номер перед тем, как писать. После десятков заказов легко запомнить правильные цифры в неправильном порядке.',app:'В ПРИЛОЖЕНИИ',not:'НЕ ТАК',why:'Если в приложении 726, значит правильный номер только 726.'},
      writing:{step:'03 / ПИШИ РАЗБОРЧИВО',title:'Другой человек это прочитает?',lead:'Все пишут цифры по-разному, и это нормально. Главное, чтобы другой человек сразу понял твой номер.',question:'КАКОЙ ЗДЕСЬ НОМЕР?',answers:['939','959','439','Вообще без понятия.'],feedback:['Ого. Да ты Ванга. Это правда 939. Но вообще-то угадывать мы не должны.','Да... мы тоже так подумали. А это, прикинь, 939.','Если честно, логичная версия. Но это каким-то образом 939.','Мы тоже. И в этом как раз проблема. Это 939.']},
      visible:{step:'04 / НОМЕР ДОЛЖНО БЫТЬ ВИДНО',title:'Сначала расправь боковую сторону.',lead:'Перед тем как писать номер, раскрой и выровняй боковую сторону пакета.',rule:'Потом напиши номер заказа КРУПНО. Его должно быть видно, не двигая пакет.'},
      together:{step:'05 / ДЕРЖИ ЗАКАЗ ВМЕСТЕ',title:'Один заказ. Одно место.',lead:'Все пакеты одного заказа должны стоять вместе.',why:'Если в заказе три пакета, все три должны быть в одном месте. Никто не должен искать остальные на другой полке.',rule1:'Напиши номер заказа на каждом пакете.',rule2:'Поставь все пакеты заказа рядом друг с другом.',cold:'ЕСЛИ ОДИН ПАКЕТ НУЖНО ОХЛАДИТЬ, ВЕСЬ ЗАКАЗ ИДЁТ В ХОЛОДИЛЬНИК.'},
      done:{step:'06 / ДОВЕДИ ДЕЛО ДО КОНЦА',packed:'УПАКОВАНО',done:'ГОТОВО',numbered:'НОМЕР ЕСТЬ',stored:'УБРАНО',lead:'Упаковать пакеты недостаточно. Готовый заказ нужно отнести в холодильник или на правильную полку.',minimumLabel:'КОГДА СОВСЕМ ЗАПАРА:',minimum:'Хотя бы довези готовую тележку до зоны холодильников. Не оставляй её на другом конце чекера.',help:'Если никто не раскладывает пакеты и есть свободная минута, помоги убрать их на место.'},
      carts:{step:'07 / ТЕЛЕЖКИ',title:'Это не парковка тележек.',lead:'В час пик пустые тележки скапливаются очень быстро. Видишь, что их становится много, убери их.',empty:'ПУСТЫЕ ТЕЛЕЖКИ',destination:'B1-B9',clear:'Отвези их в B1-B9 рядом с хлебными полками. Не загромождай чекер.'},
      water:{step:'08 / УПАКОВКИ ВОДЫ',title:'Вода тоже идёт в пакет.',lead:'Курьеры часто забирают бумажные пакеты и забывают воду, которая стоит отдельно.',rule:'Положи упаковку воды в пакет Wolt и закрой его как обычно.'},
      listen:{step:'09 / СМОТРИ ПО СТОРОНАМ',title:'Слышишь номер? Оглянись.',call:'«СЕМЬ ЧЕТЫРЕ ЧЕТЫРЕ?»',lead:'Когда менеджер смены называет номер, проверь пакеты рядом. Если видишь нужный, скажи.',why:'Быстрый ответ может сэкономить несколько минут поисков.'},
      checklist:{step:'10 / ФИНАЛЬНАЯ ПРОВЕРКА',title:'Перед тем как уйти.',items:['Правильный номер заказа','Номер есть на каждом пакете','Написан крупно и разборчиво','Боковая сторона смотрит наружу','Все пакеты стоят вместе','Правильная полка или холодильник','Готовая тележка не брошена','Пустые тележки не мешают у чекера'],closing:'ОБЛЕГЧИ РАБОТУ ТОМУ, КТО ИДЁТ СЛЕДОМ.',done:'ГОТОВО ✓'}
    },
    knowledge:{step:'ФИНАЛ / БЫСТРАЯ ПРОВЕРКА',title:'Готов к часу пик?',intro:'Шесть коротких ситуаций. Примерно минута.',question:'ВОПРОС {current} / {total}',score:'Правильных ответов: {score}',continue:'Дальше →',result:'Показать результат →',correct:'Верно.',incorrect:'Не совсем.',ready:'К ЧАСУ ПИК ГОТОВ ✓',review:'Стоит повторить:',questions:[
      {q:'В зону упаковки привезли тележку, но одного товара ещё нет. Заказ готов к упаковке?',a:['Да, можно начать, пока товар несут.','Нет, сначала весь заказ должен быть готов.','Только если заказ маленький.'],correct:1,rule:'Готов к упаковке значит, что весь заказ собран до начала упаковки.',label:'Готово значит готово'},
      {q:'Ты запомнил номер заказа после того, как посмотрел в приложение. Что делать?',a:['Написать по памяти.','Ещё раз посмотреть в приложение перед записью.','Попросить кого-нибудь угадать.'],correct:1,rule:'Снова проверь приложение. Не пиши номер заказа по памяти.',label:'Проверь номер'},
      {q:'У заказа 744 три пакета. Куда их поставить?',a:['Вместе в одном месте.','Куда угодно, где есть место.','На разные полки.'],correct:0,rule:'Все пакеты одного заказа должны стоять вместе в одном месте.',label:'Держи заказ вместе'},
      {q:'Один пакет заказа нужно поставить в холодильник. Что делать с остальными?',a:['Убрать только холодный пакет.','Поставить в холодильник весь заказ.','Оставить их у чекера.'],correct:1,rule:'Если один пакет нужно охладить, весь заказ идёт в холодильник.',label:'Весь заказ в холодильник'},
      {q:'У чекера скопились пустые тележки. Куда их отвезти?',a:['К холодильнику.','В B1-B9 рядом с хлебными полками.','Куда угодно за пределами зоны упаковки.'],correct:1,rule:'Отвези пустые тележки в B1-B9 и освободи чекер.',label:'Тележки в B1-B9'},
      {q:'В заказе есть упаковка воды. Как её упаковать?',a:['Оставить отдельно рядом с пакетами.','Положить в пакет Wolt и закрыть его.','Передать курьеру отдельно.'],correct:1,rule:'Упаковка воды должна быть в пакете Wolt, чтобы её не забыли.',label:'Вода идёт в пакет'}
    ]}
  },
  en: {
    meta:{name:'English',choose:'CHOOSE YOUR LANGUAGE',switch:'Language',brand:'PEAK HOURS'},
    signature:'Made with love and mild peak-hour trauma by Alina',
    hero:{duration:'3 min guide',kicker:'QUICK TEAM GUIDE',peak:'PEAK',hours:'HOURS.',intro:'A few seconds now can save several minutes at the checker.',rule:"MAKE THE NEXT PERSON'S JOB EASIER.",start:'Start the quick guide'},
    introduction:{heading:'PEAK HOURS GET MESSY FAST.',p1:'When there are dozens of finished orders and a line of couriers at the checker, small things start making a huge difference.',p2:'This guide has a few simple rules that make orders easier to pack, find and hand out.',p3:'Most of them take a few seconds. They save everyone a lot more time later.',goalLabel:'THE GOAL IS SIMPLE:',goal:"MAKE THE NEXT PERSON'S JOB EASIER."},
    labels:{before:'BEFORE',after:'AFTER',wrong:'× WRONG',right:'✓ RIGHT'},
    photos:{folded:'The side of the bag is still folded.',flat:'The side of the bag is open and flat.',separate:'Bags from one order are stored in different places.',together:'Every bag from each order is stored together.',finishedCarts:'Finished orders are left on carts around the checker.',carts:'Empty carts are blocking the checker.',waterLoose:'A water multipack is loose outside the order bags.',waterBag:'A water multipack is inside a Wolt bag.',numberStyles:'A reference showing different readable styles of handwritten numbers.',handwriting939:'A real bag label with the handwritten order number 939.'},
    sections:{
      ready:{step:'01 / READY MEANS READY',title:"If it's here, it's ready.",equation:'PACKING AREA = READY TO PACK',cart:'CART',area:'PACKING AREA',ready:'READY TO PACK',notReady:'NOT READY YET',flowLabel:'Cart to packing area to ready to pack',lead:'A packer should be able to start right away.',noteTitle:'Still missing something?',note:"Tell the packer and keep the cart out of the packing area until the order is ready. Do not keep adding items after packing has started."},
      number:{step:'02 / CHECK THE NUMBER',title:'Look once. Then look again.',lead:'Check the number before you write it. After dozens of orders, it is easy to remember the right digits in the wrong order.',app:'APP SAYS',not:'NOT',why:'If the app says 726, only 726 is correct.'},
      writing:{step:'03 / WRITE IT CLEARLY',title:'Can someone else read it?',lead:'People write numbers differently. That is fine. The important thing is that someone else can read yours immediately.',question:'WHAT NUMBER IS THIS?',answers:['939','959','439','Honestly, no idea.'],feedback:['Okay, wow. Are you psychic? It is 939. But we really should not have to guess.','Yeah... we could see that too. Apparently it is 939.','Honestly, fair guess. Somehow this is 939.','Same. And that is exactly the problem. It is 939.']},
      visible:{step:'04 / MAKE IT VISIBLE',title:'Flatten the side first.',lead:'Before you write the number, open the side of the bag and flatten it.',rule:'Then write the order number BIG. It should be easy to see without moving the bag.'},
      together:{step:'05 / KEEP IT TOGETHER',title:'One order. One place.',lead:'All bags from the same order stay together.',why:'If an order has three bags, I should find all three in the same place. Nobody should have to search another shelf for the rest.',rule1:'Write the order number on every bag.',rule2:'Put every bag from the order directly next to the others.',cold:'IF ONE BAG NEEDS THE FRIDGE, THE WHOLE ORDER GOES IN.'},
      done:{step:'06 / FINISH THE JOB',packed:'PACKED',done:'DONE',numbered:'NUMBERED',stored:'STORED',lead:'Packing the bags is not the end of the job. Finished orders need to reach the fridge or the correct shelf.',minimumLabel:'WHEN IT IS VERY BUSY:',minimum:"At least bring the finished cart to the fridge area. Do not leave it somewhere across the checker.",help:'If nobody is organizing the bags and you have a moment, help put them away.'},
      carts:{step:'07 / CARTS',title:'This is not cart parking.',lead:'Empty carts pile up very quickly during peak hours. If you see this happening, move them.',empty:'EMPTY CARTS',destination:'B1-B9',clear:'Move them to B1-B9 near the bread shelves. Keep the checker clear.'},
      water:{step:'08 / WATER MULTIPACKS',title:'Water goes in a bag.',lead:'Couriers often grab the paper bags and forget loose water behind.',rule:'Put the water inside a Wolt bag and close it normally.'},
      listen:{step:'09 / STAY AWARE',title:'Hear a number? Look around.',call:'"SEVEN FOUR FOUR?"',lead:'When a shift manager calls a number, check the bags around you. If you see it, say so.',why:'A quick answer can save several minutes of searching.'},
      checklist:{step:'10 / THE FINAL CHECK',title:'Before you walk away.',items:['Correct order number','Number on every bag','Big and readable','Side facing outward','All bags together','Correct shelf or fridge','Finished cart is not abandoned','Empty carts do not block the checker'],closing:"MAKE THE NEXT PERSON'S JOB EASIER.",done:'DONE ✓'}
    },
    knowledge:{step:'FINAL / KNOWLEDGE CHECK',title:'Ready for peak hours?',intro:'Six quick situations. About one minute.',question:'QUESTION {current} / {total}',score:'{score} correct',continue:'Continue →',result:'See result →',correct:'Correct.',incorrect:'Not quite.',ready:'READY FOR PEAK HOURS ✓',review:'Quick review:',questions:[
      {q:'A cart enters the packing area, but one item is still missing. Is it ready to pack?',a:['Yes. Packing can start while the item arrives.','No. The whole order must be ready first.','Only if the order is small.'],correct:1,rule:'READY TO PACK means the whole order is ready before packing starts.',label:'Ready means ready'},
      {q:'You remember the order number after looking at the app. What should you do?',a:['Write it from memory.','Look at the app again before writing.','Ask someone else to guess.'],correct:1,rule:'Check the app again. Do not write the order number from memory.',label:'Check the number'},
      {q:'Order 744 has three bags. Where should they go?',a:['Together in the same place.','Anywhere with free space.','On separate shelves.'],correct:0,rule:'Every bag from one order stays together in one place.',label:'Keep the order together'},
      {q:'One bag in an order needs refrigeration. What about the other bags?',a:['Only the cold bag goes in.','The whole order goes in the fridge.','Leave them at the checker.'],correct:1,rule:'If one bag needs the fridge, the whole order goes in.',label:'Whole order in the fridge'},
      {q:'Empty carts are building up around the checker. Where do they go?',a:['Next to the fridge.','B1-B9 near the bread shelves.','Anywhere outside the packing area.'],correct:1,rule:'Move empty carts to B1-B9 and keep the checker clear.',label:'Empty carts to B1-B9'},
      {q:'An order includes a water multipack. How should it be packed?',a:['Leave it loose beside the bags.','Put it inside a Wolt bag and close it.','Hand it separately to the courier.'],correct:1,rule:'Water multipacks go inside a Wolt bag so they do not get left behind.',label:'Water goes in a bag'}
    ]}
  },
  he: {
    meta:{name:'עברית',choose:'בחרו שפה',switch:'שפה',brand:'שעות עומס'},
    signature:'נעשה באהבה ועם קצת טראומה ממשמרות עומס. אלינה',
    hero:{duration:'מדריך של 3 דקות',kicker:'מדריך קצר לצוות',peak:'שעות',hours:'עומס.',intro:'כמה שניות עכשיו יכולות לחסוך כמה דקות בצ׳קר.',rule:'להקל על מי שעובד אחריך.',start:'מתחילים'},
    introduction:{heading:'בשעות עומס נהיה בלגן מהר.',p1:'כשעשרות הזמנות מוכנות ושליחים מחכים בצ׳קר, הדברים הקטנים מתחילים להשפיע מאוד.',p2:'במדריך הזה יש כמה כללים פשוטים שעוזרים לארוז, למצוא ולמסור הזמנות.',p3:'רובם לוקחים כמה שניות וחוסכים לכולם הרבה יותר זמן אחר כך.',goalLabel:'המטרה פשוטה:',goal:'להקל על מי שעובד אחריך.'},
    labels:{before:'לפני',after:'אחרי',wrong:'× לא נכון',right:'✓ נכון'},
    photos:{folded:'צד השקית עדיין מקופל.',flat:'צד השקית פתוח ושטוח.',separate:'שקיות מאותה הזמנה נמצאות במקומות שונים.',together:'כל השקיות מכל הזמנה נמצאות יחד.',finishedCarts:'הזמנות מוכנות נשארו על עגלות ליד הצ׳קר.',carts:'עגלות ריקות חוסמות את הצ׳קר.',waterLoose:'מארז מים נשאר מחוץ לשקיות ההזמנה.',waterBag:'מארז מים נמצא בתוך שקית וולט.',numberStyles:'דוגמה לסגנונות שונים וברורים של ספרות בכתב יד.',handwriting939:'תווית אמיתית על שקית עם מספר ההזמנה 939 בכתב יד.'},
    sections:{
      ready:{step:'01 / מוכן זה מוכן',title:'אם זה כאן, זה מוכן.',equation:'אזור אריזה = מוכן לאריזה',cart:'עגלה',area:'אזור אריזה',ready:'מוכן לאריזה',notReady:'עדיין לא מוכן',flowLabel:'עגלה אל אזור האריזה ומשם למוכן לאריזה',lead:'האורז צריך להיות מסוגל להתחיל מיד.',noteTitle:'עדיין חסר משהו?',note:'עדכנו את האורז והשאירו את העגלה מחוץ לאזור האריזה עד שהכול מוכן. אל תוסיפו מוצרים אחרי שהאריזה התחילה.'},
      number:{step:'02 / בודקים את המספר',title:'מסתכלים פעם אחת. ואז שוב.',lead:'בדקו את המספר לפני שאתם כותבים. אחרי עשרות הזמנות קל מאוד להחליף בין הספרות.',app:'באפליקציה',not:'לא',why:'אם 726 הופך ל-762, נחפש הזמנה שלא קיימת.'},
      writing:{step:'03 / כותבים ברור',title:'מישהו אחר יכול לקרוא את זה?',lead:'אנשים כותבים מספרים בצורות שונות וזה בסדר. מה שחשוב הוא שמישהו אחר יוכל לקרוא את המספר מיד.',question:'איזה מספר זה?',answers:['939','959','439','באמת שאין לי מושג.'],feedback:['וואו. אתם קוראים מחשבות? זה באמת 939. אבל לא אמורים לנחש.','כן... גם אנחנו רואים 959. מתברר שזה 939.','בכנות, ניחוש הוגן. איכשהו זה 939.','גם לנו אין מושג. וזאת בדיוק הבעיה. זה 939.']},
      visible:{step:'04 / הופכים את המספר לגלוי',title:'קודם משטחים את הצד.',lead:'לפני שכותבים את המספר, פותחים את צד השקית ומשטחים אותו.',rule:'אחר כך כותבים את מספר ההזמנה בגדול. צריך לראות אותו בלי להזיז את השקית.'},
      together:{step:'05 / שומרים את ההזמנה יחד',title:'הזמנה אחת. מקום אחד.',lead:'כל השקיות מאותה הזמנה נשארות יחד.',why:'אם להזמנה יש שלוש שקיות, צריך למצוא את שלושתן באותו מקום. אף אחד לא צריך לחפש את השאר במדף אחר.',rule1:'כותבים את מספר ההזמנה על כל שקית.',rule2:'מניחים את כל שקיות ההזמנה צמודות זו לזו.',cold:'אם שקית אחת צריכה קירור, כל ההזמנה נכנסת למקרר.'},
      done:{step:'06 / מסיימים את העבודה',packed:'ארוז',done:'מוכן',numbered:'ממוספר',stored:'במקום',lead:'אריזת השקיות היא לא סוף העבודה. הזמנות מוכנות צריכות להגיע למקרר או למדף הנכון.',minimumLabel:'כשעמוס מאוד:',minimum:'לפחות הביאו את העגלה המוכנה לאזור המקררים. אל תשאירו אותה בצד השני של הצ׳קר.',help:'אם אף אחד לא מסדר את השקיות ויש לכם רגע, עזרו להכניס אותן למקום.'},
      carts:{step:'07 / עגלות',title:'זה לא חניון עגלות.',lead:'עגלות ריקות מצטברות מהר מאוד בשעות עומס. אם זה מתחיל לקרות, מזיזים אותן.',empty:'עגלות ריקות',destination:'B1-B9',clear:'מעבירים ל-B1-B9 ליד מדפי הלחם. משאירים את הצ׳קר פנוי.'},
      water:{step:'08 / מארזי מים',title:'מים נכנסים לשקית.',lead:'שליחים לוקחים את שקיות הנייר ולפעמים משאירים מים חופשיים מאחור.',rule:'מכניסים את המים לשקית וולט וסוגרים אותה כרגיל.'},
      listen:{step:'09 / נשארים קשובים',title:'שמעתם מספר? תסתכלו מסביב.',call:'״שבע ארבע ארבע?״',lead:'כשאחמ״ש קורא מספר, בדקו את השקיות לידכם. אם מצאתם, תגידו.',why:'תשובה מהירה יכולה לחסוך כמה דקות של חיפוש.'},
      checklist:{step:'10 / בדיקה אחרונה',title:'לפני שממשיכים הלאה.',items:['מספר הזמנה נכון','מספר על כל שקית','גדול וברור','הצד פונה החוצה','כל השקיות יחד','מדף או מקרר נכון','עגלה מוכנה לא ננטשה','עגלות ריקות לא חוסמות את הצ׳קר'],closing:'להקל על מי שעובד אחריך.',done:'סיימנו ✓'}
    },
    knowledge:{step:'סיום / בדיקת ידע',title:'מוכנים לשעות עומס?',intro:'שישה מצבים קצרים. בערך דקה.',question:'שאלה {current} מתוך {total}',score:'{score} נכונות',continue:'המשך ←',result:'לתוצאה ←',correct:'נכון.',incorrect:'לא בדיוק.',ready:'מוכנים לשעות עומס ✓',review:'כדאי לחזור על:',questions:[
      {q:'עגלה נכנסה לאזור האריזה אבל עדיין חסר מוצר. היא מוכנה לאריזה?',a:['כן. אפשר להתחיל והמוצר יגיע אחר כך.','לא. כל ההזמנה צריכה להיות מוכנה קודם.','רק אם זו הזמנה קטנה.'],correct:1,rule:'מוכן לאריזה אומר שכל ההזמנה מוכנה לפני שמתחילים.',label:'מוכן זה מוכן'},
      {q:'אתם זוכרים את מספר ההזמנה מהאפליקציה. מה עושים?',a:['כותבים מהזיכרון.','מסתכלים שוב באפליקציה לפני הכתיבה.','מבקשים ממישהו לנחש.'],correct:1,rule:'בודקים שוב באפליקציה. לא כותבים מספר מהזיכרון.',label:'בדיקת המספר'},
      {q:'להזמנה 744 יש שלוש שקיות. איפה מניחים אותן?',a:['יחד באותו מקום.','בכל מקום שיש בו מקום פנוי.','במדפים נפרדים.'],correct:0,rule:'כל השקיות מאותה הזמנה נשארות יחד במקום אחד.',label:'שומרים הזמנה יחד'},
      {q:'שקית אחת בהזמנה צריכה קירור. מה עם שאר השקיות?',a:['רק השקית הקרה נכנסת.','כל ההזמנה נכנסת למקרר.','משאירים אותן בצ׳קר.'],correct:1,rule:'אם שקית אחת צריכה קירור, כל ההזמנה נכנסת למקרר.',label:'כל ההזמנה במקרר'},
      {q:'עגלות ריקות מצטברות ליד הצ׳קר. לאן הן הולכות?',a:['ליד המקרר.','ל-B1-B9 ליד מדפי הלחם.','לכל מקום מחוץ לאזור האריזה.'],correct:1,rule:'מעבירים עגלות ריקות ל-B1-B9 ומשאירים את הצ׳קר פנוי.',label:'עגלות ל-B1-B9'},
      {q:'בהזמנה יש מארז מים. איך אורזים אותו?',a:['משאירים אותו ליד השקיות.','מכניסים לשקית וולט וסוגרים.','מוסרים בנפרד לשליח.'],correct:1,rule:'מארזי מים נכנסים לשקית וולט כדי שלא יישארו מאחור.',label:'מים בתוך שקית'}
    ]}
  },
  th: {
    meta:{name:'ไทย',choose:'เลือกภาษา',switch:'ภาษา',brand:'ช่วงเวลาเร่งด่วน'},
    signature:'ทำด้วยความรักและความหลอนนิด ๆ จากช่วงพีก อลีนา',
    hero:{duration:'คู่มือ 3 นาที',kicker:'คู่มือสั้นสำหรับทีม',peak:'ช่วงเวลา',hours:'เร่งด่วน',intro:'ใช้เวลาไม่กี่วินาทีตอนนี้ ช่วยประหยัดเวลาหลายนาทีที่จุดเช็กเกอร์ได้',rule:'ช่วยให้งานของคนถัดไปง่ายขึ้น',start:'เริ่มคู่มือ'},
    introduction:{heading:'ช่วงเร่งด่วนวุ่นวายได้เร็วมาก',p1:'เมื่อมีออเดอร์เสร็จหลายสิบรายการและไรเดอร์ต่อแถวที่จุดเช็กเกอร์ เรื่องเล็ก ๆ จะมีผลมาก',p2:'คู่มือนี้มีเพียงกฎง่าย ๆ ที่ช่วยให้แพ็ก หา และส่งมอบออเดอร์ได้ง่ายขึ้น',p3:'ส่วนใหญ่ใช้เวลาเพียงไม่กี่วินาที แต่ช่วยประหยัดเวลาให้ทุกคนในภายหลัง',goalLabel:'เป้าหมายง่าย ๆ คือ',goal:'ช่วยให้งานของคนถัดไปง่ายขึ้น'},
    labels:{before:'ก่อน',after:'หลัง',wrong:'× ผิด',right:'✓ ถูก'},
    photos:{folded:'ด้านข้างของถุงยังพับอยู่',flat:'ด้านข้างของถุงเปิดและแบนแล้ว',separate:'ถุงของออเดอร์เดียวกันอยู่คนละที่',together:'ถุงของแต่ละออเดอร์อยู่ด้วยกัน',finishedCarts:'ออเดอร์ที่เสร็จแล้วถูกทิ้งไว้บนรถเข็นรอบจุดเช็กเกอร์',carts:'รถเข็นเปล่าขวางจุดเช็กเกอร์',waterLoose:'แพ็กน้ำอยู่นอกถุงออเดอร์',waterBag:'แพ็กน้ำอยู่ในถุง Wolt',numberStyles:'ตัวอย่างรูปแบบตัวเลขลายมือที่แตกต่างกันและอ่านได้',handwriting939:'ป้ายบนถุงจริงที่เขียนหมายเลขออเดอร์ 939 ด้วยลายมือ'},
    sections:{
      ready:{step:'01 / พร้อมคือพร้อม',title:'ถ้าอยู่ตรงนี้ ต้องพร้อมแพ็ก',equation:'พื้นที่แพ็ก = พร้อมแพ็ก',cart:'รถเข็น',area:'พื้นที่แพ็ก',ready:'พร้อมแพ็ก',notReady:'ยังไม่พร้อม',flowLabel:'รถเข็นไปพื้นที่แพ็กแล้วพร้อมแพ็ก',lead:'คนแพ็กต้องเริ่มงานได้ทันที',noteTitle:'ยังขาดของอยู่หรือไม่?',note:'บอกคนแพ็กและเก็บรถเข็นไว้นอกพื้นที่แพ็กจนกว่าออเดอร์จะพร้อม อย่าเติมของหลังจากเริ่มแพ็กแล้ว'},
      number:{step:'02 / ตรวจเลขออเดอร์',title:'ดูหนึ่งครั้ง แล้วดูอีกครั้ง',lead:'ตรวจเลขก่อนเขียน หลังจากทำออเดอร์มาหลายรายการ เราสลับตัวเลขได้ง่าย',app:'ในแอป',not:'ไม่ใช่',why:'ถ้า 726 กลายเป็น 762 เราจะหาออเดอร์ที่ไม่มีอยู่จริง'},
      writing:{step:'03 / เขียนให้อ่านง่าย',title:'คนอื่นอ่านออกไหม?',lead:'แต่ละคนเขียนตัวเลขไม่เหมือนกัน ไม่เป็นไร สิ่งสำคัญคือคนอื่นต้องอ่านของคุณออกทันที',question:'นี่คือเลขอะไร?',answers:['939','959','439','ไม่รู้จริง ๆ'],feedback:['โอ้โห อ่านใจได้หรือเปล่า? มันคือ 939 จริง ๆ แต่เราไม่ควรต้องเดา','ใช่... เราก็มองเป็น 959 เหมือนกัน แต่เขาว่ามันคือ 939','พูดตามตรง เดาได้สมเหตุสมผลมาก แต่ยังไงไม่รู้มันคือ 939','เหมือนกันเลย และนั่นแหละคือปัญหา มันคือ 939']},
      visible:{step:'04 / ทำให้มองเห็น',title:'คลี่ด้านข้างก่อน',lead:'ก่อนเขียนเลข ให้เปิดด้านข้างของถุงและคลี่ให้แบน',rule:'จากนั้นเขียนเลขออเดอร์ให้ใหญ่ ต้องมองเห็นได้โดยไม่ต้องขยับถุง'},
      together:{step:'05 / เก็บออเดอร์ไว้ด้วยกัน',title:'หนึ่งออเดอร์ หนึ่งที่',lead:'ถุงทั้งหมดของออเดอร์เดียวกันต้องอยู่ด้วยกัน',why:'ถ้าออเดอร์มีสามถุง ต้องเจอทั้งสามถุงในที่เดียว ไม่มีใครควรต้องหาอีกถุงบนชั้นอื่น',rule1:'เขียนเลขออเดอร์บนทุกถุง',rule2:'วางถุงทั้งหมดของออเดอร์ไว้ติดกัน',cold:'ถ้าถุงหนึ่งต้องแช่เย็น ให้นำทั้งออเดอร์เข้าตู้เย็น'},
      done:{step:'06 / ทำงานให้เสร็จ',packed:'แพ็กแล้ว',done:'เสร็จ',numbered:'มีเลขแล้ว',stored:'เก็บแล้ว',lead:'แพ็กถุงเสร็จยังไม่ใช่จบงาน ออเดอร์ที่เสร็จต้องไปที่ตู้เย็นหรือชั้นที่ถูกต้อง',minimumLabel:'เมื่อยุ่งมาก:',minimum:'อย่างน้อยให้นำรถเข็นที่เสร็จแล้วไปบริเวณตู้เย็น อย่าทิ้งไว้ฝั่งอื่นของจุดเช็กเกอร์',help:'ถ้าไม่มีใครกำลังจัดถุงและคุณมีเวลา ช่วยนำถุงไปเก็บ'},
      carts:{step:'07 / รถเข็น',title:'ตรงนี้ไม่ใช่ที่จอดรถเข็น',lead:'รถเข็นเปล่าสะสมเร็วมากในช่วงเร่งด่วน ถ้าเห็นว่าเริ่มกอง ให้ย้ายออก',empty:'รถเข็นเปล่า',destination:'B1-B9',clear:'ย้ายไป B1-B9 ใกล้ชั้นขนมปัง รักษาพื้นที่เช็กเกอร์ให้โล่ง'},
      water:{step:'08 / แพ็กน้ำ',title:'น้ำต้องใส่ถุง',lead:'ไรเดอร์มักหยิบถุงกระดาษและลืมน้ำที่วางแยกไว้',rule:'ใส่แพ็กน้ำในถุง Wolt แล้วปิดถุงตามปกติ'},
      listen:{step:'09 / คอยฟังรอบตัว',title:'ได้ยินเลขไหม? มองรอบตัว',call:'“เจ็ด สี่ สี่?”',lead:'เมื่อผู้จัดการกะเรียกหมายเลข ให้ดูถุงรอบตัว ถ้าเจอให้บอกทันที',why:'คำตอบสั้น ๆ ช่วยประหยัดเวลาค้นหาได้หลายนาที'},
      checklist:{step:'10 / ตรวจครั้งสุดท้าย',title:'ก่อนเดินออกไป',items:['เลขออเดอร์ถูกต้อง','มีเลขบนทุกถุง','ใหญ่และอ่านง่าย','ด้านข้างหันออก','ถุงทั้งหมดอยู่ด้วยกัน','ชั้นหรือตู้เย็นถูกต้อง','ไม่ทิ้งรถเข็นที่เสร็จแล้ว','รถเข็นเปล่าไม่ขวางจุดเช็กเกอร์'],closing:'ช่วยให้งานของคนถัดไปง่ายขึ้น',done:'เสร็จ ✓'}
    },
    knowledge:{step:'สุดท้าย / ทบทวนความเข้าใจ',title:'พร้อมสำหรับช่วงเร่งด่วนไหม?',intro:'หกสถานการณ์สั้น ๆ ใช้เวลาประมาณหนึ่งนาที',question:'คำถาม {current} / {total}',score:'ถูก {score} ข้อ',continue:'ต่อไป →',result:'ดูผล →',correct:'ถูกต้อง',incorrect:'ยังไม่ถูก',ready:'พร้อมสำหรับช่วงเร่งด่วน ✓',review:'ทบทวนอีกครั้ง:',questions:[
      {q:'รถเข็นเข้าพื้นที่แพ็ก แต่ยังขาดสินค้าหนึ่งชิ้น พร้อมแพ็กหรือยัง?',a:['พร้อม เริ่มแพ็กก่อนได้','ยัง ต้องให้ออเดอร์ครบก่อน','พร้อมเฉพาะออเดอร์เล็ก'],correct:1,rule:'พร้อมแพ็กหมายถึงทั้งออเดอร์พร้อมก่อนเริ่มแพ็ก',label:'พร้อมคือพร้อม'},
      {q:'คุณจำเลขออเดอร์จากแอปได้ ควรทำอะไร?',a:['เขียนจากความจำ','ดูในแอปอีกครั้งก่อนเขียน','ให้คนอื่นเดา'],correct:1,rule:'ตรวจแอปอีกครั้ง อย่าเขียนเลขออเดอร์จากความจำ',label:'ตรวจเลขออเดอร์'},
      {q:'ออเดอร์ 744 มีสามถุง ควรวางที่ไหน?',a:['วางด้วยกันในที่เดียว','วางตรงไหนที่มีที่ว่าง','แยกคนละชั้น'],correct:0,rule:'ถุงทั้งหมดของออเดอร์เดียวกันต้องอยู่ด้วยกันในที่เดียว',label:'เก็บออเดอร์ด้วยกัน'},
      {q:'หนึ่งถุงในออเดอร์ต้องแช่เย็น แล้วถุงอื่นล่ะ?',a:['แช่เฉพาะถุงเย็น','นำทั้งออเดอร์เข้าตู้เย็น','ทิ้งไว้ที่จุดเช็กเกอร์'],correct:1,rule:'ถ้าหนึ่งถุงต้องแช่เย็น ให้นำทั้งออเดอร์เข้าตู้เย็น',label:'ทั้งออเดอร์เข้าตู้เย็น'},
      {q:'รถเข็นเปล่ากำลังกองรอบจุดเช็กเกอร์ ต้องย้ายไปไหน?',a:['ข้างตู้เย็น','B1-B9 ใกล้ชั้นขนมปัง','ที่ไหนก็ได้นอกพื้นที่แพ็ก'],correct:1,rule:'ย้ายรถเข็นเปล่าไป B1-B9 และรักษาจุดเช็กเกอร์ให้โล่ง',label:'รถเข็นไป B1-B9'},
      {q:'ออเดอร์มีแพ็กน้ำ ควรแพ็กอย่างไร?',a:['วางแยกไว้ข้างถุง','ใส่ในถุง Wolt แล้วปิด','ส่งให้ไรเดอร์แยกต่างหาก'],correct:1,rule:'แพ็กน้ำต้องอยู่ในถุง Wolt เพื่อไม่ให้ถูกลืม',label:'น้ำต้องใส่ถุง'}
    ]}
  }
};
