window.translations = {
  ru: {
    meta:{name:'Русский',choose:'ВЫБЕРИ ЯЗЫК',switch:'Язык',brand:'ЧАС ПИК'},
    signature:'С любовью и лёгкой травмой от запары, Алина',
    hero:{duration:'Гайд на 3 минуты',kicker:'КОРОТКИЙ ГАЙД ДЛЯ КОМАНДЫ',peak:'ЧАС',hours:'ПИК.',intro:'Пара секунд сейчас может сэкономить несколько минут у чекера.',rule:'Облегчи работу тому, кто идёт следом.',start:'ОТКРЫТЬ КОРОТКИЙ ГАЙД'},
    introduction:{heading:'В час пик бардак начинается быстро.',p1:'Когда готовы десятки заказов, а у чекера очередь курьеров, любая мелочь сильно влияет на работу.',p2:'Здесь несколько простых правил, с которыми заказы легче упаковывать, находить и выдавать.',p3:'На каждое уходит пара секунд, а потом вся команда экономит гораздо больше времени.',goalLabel:'ЦЕЛЬ ПРОСТАЯ:',goal:'Облегчи работу тому, кто идёт следом.'},
    labels:{before:'ДО',after:'ПОСЛЕ',wrong:'× НЕПРАВИЛЬНО',right:'✓ ПРАВИЛЬНО'},
    photos:{folded:'Боковая сторона пакета всё ещё сложена.',flat:'Боковая сторона пакета расправлена.',separate:'Пакеты одного заказа без причины стоят в разных местах.',together:'Пакеты одного заказа стоят рядом.',finishedCarts:'Готовые заказы остались на тележках у чекера.',carts:'Пустые тележки загородили чекер.',waterLoose:'Упаковка воды стоит отдельно от пакетов заказа.',waterBag:'Упаковка воды лежит внутри пакета Wolt.',numberStyles:'Примеры разных, но разборчивых вариантов написания цифр.',handwriting939:'Настоящая наклейка на пакете с номером заказа 939, написанным от руки.',customerNameBefore:'На пакете есть пожелание, но нет имени клиента.',customerNameAfter:'На том же пакете ясно написано имя Daniel.',diaperWrong:'Упаковка подгузников лежит отдельно — только с наклейкой Wolt.',diaperRight:'Упаковка подгузников находится внутри бумажного пакета Wolt.'},
    sections:{
      ready:{step:'01 / ГОТОВО ЗНАЧИТ ГОТОВО',title:'Если заказ здесь — он готов.',equation:'ЗОНА УПАКОВКИ = МОЖНО УПАКОВЫВАТЬ',cart:'ТЕЛЕЖКА',area:'ЗОНА УПАКОВКИ',ready:'МОЖНО УПАКОВЫВАТЬ',notReady:'ЕЩЁ НЕ ГОТОВО',flowLabel:'Тележка едет в зону упаковки, когда заказ полностью готов',lead:'Упаковщик должен сразу начать работу.',noteTitle:'Чего-то не хватает?',note:'Скажи упаковщику и оставь тележку за пределами зоны упаковки, пока заказ не будет готов. Не добавляй товары после начала упаковки.'},
      number:{step:'02 / ПРОВЕРЬ НОМЕР',title:'«Семь раз проверь, один раз напиши»',lead:'Проверь номер перед тем, как писать. После десятков заказов цифры очень легко перепутать местами.',app:'В ПРИЛОЖЕНИИ',not:'НЕ ТАК',why:'Если в приложении 726, правильный номер — только 726.'},
      writing:{step:'03 / ПИШИ РАЗБОРЧИВО',title:'Другой человек это прочитает?',lead:'Все пишут цифры по-разному, и это нормально. Главное, чтобы другой человек сразу понял твой номер.',question:'Какой здесь номер?',choose:'Выбери вариант:',answers:['435','439','939','935','545','539'],feedback:['Да... вполне можно было так подумать. Но это 939.','Да... вполне можно было так подумать. Но это 939.','Ого. Да ты Ванга. Это правда 939. Но угадывать мы вообще-то не должны.','Да... вполне можно было так подумать. Но это 939.','Да... вполне можно было так подумать. Но это 939.','Да... вполне можно было так подумать. Но это 939.']},
      visible:{step:'04 / НОМЕР ДОЛЖНО БЫТЬ ВИДНО',title:'Сначала расправь боковую сторону.',lead:'Перед тем как писать номер, раскрой и выровняй боковую сторону пакета.',rule:'Потом напиши номер заказа КРУПНО. Его должно быть видно, не двигая пакет.',tip:'Если холодильник забит, номер можно написать ниже на боковой стороне пакета. Так его будет проще увидеть.'},
      customerName:{step:'ИМЯ КЛИЕНТА',title:'Красиво. А кому?',lead:'Всегда пиши на пакете имя клиента.',detail:'Перепиши имя из приложения. «Шаббат шалом» или другое пожелание не заменяет имя клиента.',playful:'Шаббат шалом — это прекрасно. Но кому?'},
      together:{step:'05 / ДЕРЖИ ЗАКАЗ РЯДОМ',title:'Один заказ. Держим рядом.',lead:'По возможности держи пакеты одного заказа вместе.',why:'Если места хватает, не разделяй один заказ по разным полкам или зонам без причины.',rule1:'Напиши номер заказа на каждом пакете.',rule2:'Если места хватает, поставь пакеты заказа рядом.',fridgeFull:'ХОЛОДИЛЬНИК ЗАБИТ?',coldBag:'ХОЛОДНЫЙ ПАКЕТ',fridge:'ХОЛОДИЛЬНИК',restOrder:'ОСТАЛЬНЫЕ ПАКЕТЫ ЭТОГО ЗАКАЗА',crate:'СКЛАДНОЙ ЯЩИК ПОД ЭТИМ ХОЛОДИЛЬНИКОМ ИЛИ ПЕРЕД НИМ',exception:'Это исключение на случай, когда в холодильнике нет места, а не обычный способ разделять заказ.'},
      done:{step:'06 / ДОВЕДИ ДЕЛО ДО КОНЦА',packed:'УПАКОВАНО',done:'ГОТОВО',numbered:'НОМЕР ЕСТЬ',stored:'УБРАНО',lead:'Упаковать пакеты недостаточно. Готовый заказ нужно отнести в холодильник или на правильную полку.',minimumLabel:'Когда совсем запара:',minimum:'Хотя бы довези готовую тележку до зоны холодильников. Не оставляй её на другом конце чекера.',help:'Если никто не раскладывает пакеты и есть свободная минута, помоги убрать их на место.'},
      carts:{step:'07 / ТЕЛЕЖКИ',title:'Это не парковка тележек.',lead:'В час пик пустые тележки скапливаются очень быстро. Если видишь, что их становится много, убери их.',empty:'ПУСТЫЕ ТЕЛЕЖКИ',destination:'B1-B9',clear:'Отвези их в B1-B9 рядом с хлебными полками. Не загромождай чекер.'},
      water:{step:'08 / УПАКОВКИ ВОДЫ',title:'Вода тоже идёт в пакет.',lead:'Курьеры часто забирают бумажные пакеты и забывают воду, которая стоит отдельно.',rule:'Положи упаковку воды в пакет Wolt и закрой его как обычно.'},
      diapers:{step:'ПОДГУЗНИКИ',title:'Подгузники — в пакет.',lead:'Наклейка не превращает упаковку подгузников в пакет. Положи её внутрь обычного пакета Wolt.'},
      listen:{step:'09 / СМОТРИ ПО СТОРОНАМ',title:'Слышишь номер? Оглянись.',call:'«СЕМЬ ЧЕТЫРЕ ЧЕТЫРЕ?»',lead:'Когда менеджер смены называет номер, проверь пакеты рядом. Если видишь нужный, скажи.',why:'Быстрый ответ может сэкономить несколько минут поисков.'},
      checklist:{step:'10 / ФИНАЛЬНАЯ ПРОВЕРКА',title:'Перед тем как уйти.',items:['Правильный номер заказа','Номер и имя клиента есть на каждом пакете','Написано крупно и разборчиво','Боковая сторона смотрит наружу','Пакеты заказа рядом или в указанном ящике','Правильная полка или холодильник','Готовая тележка не брошена','Пустые тележки не мешают у чекера'],closing:'Облегчи работу тому, кто идёт следом.',done:'ГОТОВО ✓'}
    },
    knowledge:{step:'ФИНАЛ / БЫСТРАЯ ПРОВЕРКА',title:'Готов/а к часу пик?',intro:'Короткие ситуации по всему гайду. Примерно 2–3 минуты.',question:'ВОПРОС {current} / {total}',score:'Правильных ответов: {score}',continue:'ДАЛЬШЕ →',result:'ПОКАЗАТЬ РЕЗУЛЬТАТ →',correct:'Верно.',incorrect:'Не совсем.',ready:'К часу пик готов/а ✓',almost:'ПОЧТИ ГОТОВ/А',reviewGuide:'СТОИТ ПОВТОРИТЬ ГАЙД',review:'Повтори это:',perfect:'12/12. Ну всё, выпендривайся. Ты реально всё прочитал/а.',fromQuiz:'Из квиза',backResults:'← НАЗАД К РЕЗУЛЬТАТАМ КВИЗА',reviewLinkLabel:'Повторить правило: {title}',questions:[
      {q:'Тележка приехала в зону упаковки, но одного товара не хватает. Что делать?',a:['Начать упаковывать.','Отставить тележку, пока весь заказ не будет готов.','Добавить товар после начала упаковки.'],correct:1,rule:'Тележка въезжает в зону упаковки только с полностью готовым заказом.',label:'Готово значит готово'},
      {q:'В приложении номер 726, и тебе кажется, что ты его запомнил/а. Что писать?',a:['Ещё раз проверить приложение и написать 726.','Написать по памяти 762.','Любой вариант с этими цифрами.'],correct:0,rule:'Проверь приложение. 726 — это не 762, 267, 276, 627 или 672.',label:'Проверь номер'},
      {q:'Ты читаешь свой почерк, а коллега — нет. Так можно?',a:['Да, ведь ты знаешь номер.','Только когда нет запары.','Нет. Другой человек должен сразу прочитать номер.'],correct:2,rule:'Пиши номер так, чтобы другой человек мог сразу его прочитать.',label:'Пиши разборчиво'},
      {q:'Холодильник забит. Как написать номер?',a:['Мелко на сложенной стороне.','Расправить бок, написать крупно и, если удобнее, ниже.','Только на верхней наклейке.'],correct:1,rule:'Расправь бок и пиши крупно. Ниже на боковой стороне тоже можно, если так номер лучше видно.',label:'Номер должно быть видно'},
      {q:'На пакете написано «Шаббат шалом», но имени клиента нет. Заказ готов?',a:['Да, пожелания достаточно.','Только если хорошо виден номер.','Нет. Нужно переписать имя клиента из приложения.'],correct:2,rule:'Пожелание не заменяет настоящее имя клиента.',label:'Напиши имя клиента'},
      {q:'Для трёх пакетов одного заказа хватает места. Куда их поставить?',a:['Рядом друг с другом.','На разные полки.','Куда попадётся свободное место.'],correct:0,rule:'По возможности держи пакеты одного заказа рядом.',label:'Держи заказ рядом'},
      {q:'Холодильник забит, а один пакет нужно охладить. Куда убрать остальные?',a:['Куда угодно снаружи.','Оставить у чекера.','В указанный ящик под этим холодильником или перед ним.'],correct:2,rule:'Холодный пакет остаётся в холодильнике, остальные идут в указанный ящик под ним или перед ним.',label:'Исключение: холодильник забит'},
      {q:'Пакеты упакованы, но на них нет номера и они не убраны на место. Заказ готов?',a:['Нет. Нужно подписать и убрать его правильно.','Да, упаковка — последний шаг.','Да, если тележка полная.'],correct:0,rule:'Упаковано не значит готово. Подпиши заказ и убери его на место.',label:'Доведи дело до конца'},
      {q:'Пустые тележки мешают у чекера. Куда их отвезти?',a:['К холодильнику.','В B1-B9 рядом с хлебными полками.','Куда угодно вне зоны упаковки.'],correct:1,rule:'Отвези пустые тележки в B1-B9 и освободи чекер.',label:'Тележки в B1-B9'},
      {q:'В заказе есть упаковка воды. Как её упаковать?',a:['Оставить отдельно рядом с пакетами.','Положить в пакет Wolt.','Передать курьеру отдельно.'],correct:1,rule:'Упаковка воды должна быть внутри пакета Wolt, чтобы её не забыли.',label:'Вода идёт в пакет'},
      {q:'На упаковке подгузников есть наклейка Wolt и номер. Этого достаточно?',a:['Да, наклейка превращает её в пакет.','Только для больших упаковок.','Нет. Положи упаковку внутрь пакета Wolt.'],correct:2,rule:'Наклейка — не пакет. Подгузники кладём внутрь пакета Wolt.',label:'Подгузники — в пакет'},
      {q:'Менеджер смены называет номер заказа, и ты видишь этот заказ. Что делать?',a:['Сказать, что видишь его.','Молчать, пока не спросят второй раз.','Молча переставить заказ.'],correct:0,rule:'Быстрый ответ может сэкономить команде несколько минут поисков.',label:'Слушай и помогай'}
    ]}
  },
  en: {
    meta:{name:'English',choose:'CHOOSE YOUR LANGUAGE',switch:'Language',brand:'PEAK HOURS'},
    signature:'Made with love and mild peak-hour trauma by Alina',
    hero:{duration:'3 min guide',kicker:'QUICK TEAM GUIDE',peak:'PEAK',hours:'HOURS.',intro:'A few seconds now can save several minutes at the checker.',rule:"MAKE THE NEXT PERSON'S JOB EASIER.",start:'START THE QUICK GUIDE'},
    introduction:{heading:'PEAK HOURS GET MESSY FAST.',p1:'When there are dozens of finished orders and a line of couriers at the checker, small things start making a huge difference.',p2:'This guide has a few simple rules that make orders easier to pack, find and hand out.',p3:'Most of them take a few seconds. They save everyone a lot more time later.',goalLabel:'THE GOAL IS SIMPLE:',goal:"MAKE THE NEXT PERSON'S JOB EASIER."},
    labels:{before:'BEFORE',after:'AFTER',wrong:'× WRONG',right:'✓ RIGHT'},
    photos:{folded:'The side of the bag is still folded.',flat:'The side of the bag is open and flat.',separate:'Bags from one order are left in different places for no reason.',together:'Bags from one order are kept close together.',finishedCarts:'Finished orders are left on carts around the checker.',carts:'Empty carts are blocking the checker.',waterLoose:'A water multipack is loose outside the order bags.',waterBag:'A water multipack is inside a Wolt bag.',numberStyles:'A reference showing different readable styles of handwritten numbers.',handwriting939:'A real bag label with the handwritten order number 939.',customerNameBefore:'The bag has a greeting but no customer name.',customerNameAfter:'The same bag with Daniel clearly written on it.',diaperWrong:'A diaper pack is left loose with only a Wolt sticker.',diaperRight:'A diaper pack is placed inside a Wolt paper bag.'},
    sections:{
      ready:{step:'01 / READY MEANS READY',title:"If it's here, it's ready.",equation:'PACKING AREA = READY TO PACK',cart:'CART',area:'PACKING AREA',ready:'READY TO PACK',notReady:'NOT READY YET',flowLabel:'Cart to packing area to ready to pack',lead:'A packer should be able to start right away.',noteTitle:'Still missing something?',note:"Tell the packer and keep the cart out of the packing area until the order is ready. Do not keep adding items after packing has started."},
      number:{step:'02 / CHECK THE NUMBER',title:'Look once. Then look again.',lead:'Check the number before you write it. After dozens of orders, digits are easy to mix up.',app:'APP SAYS',not:'NOT',why:'If the app says 726, only 726 is correct.'},
      writing:{step:'03 / WRITE IT CLEARLY',title:'Can someone else read it?',lead:'People write numbers differently. That is fine. The important thing is that someone else can read yours immediately.',question:'What number is this?',choose:'Choose an answer:',answers:['435','439','939','935','545','539'],feedback:['Yeah... fair guess. It\'s actually 939.','Yeah... fair guess. It\'s actually 939.','Okay, wow. Are you psychic? It really is 939. But we shouldn\'t have to guess.','Yeah... fair guess. It\'s actually 939.','Yeah... fair guess. It\'s actually 939.','Yeah... fair guess. It\'s actually 939.']},
      visible:{step:'04 / MAKE IT VISIBLE',title:'Flatten the side first.',lead:'Before you write the number, open the side of the bag and flatten it.',rule:'Then write the order number BIG. It should be easy to see without moving the bag.',tip:'If the fridge is packed, writing the number lower on the side can make it easier to see.'},
      customerName:{step:'CUSTOMER NAME',title:'Nice message. But who is it for?',lead:"Always write the customer's name on the bag.",detail:"Copy the name from the app. 'Shabbat Shalom' or another greeting does not replace the customer's name.",playful:'Shabbat Shalom is lovely. Shabbat Shalom to whom?'},
      together:{step:'05 / KEEP IT CLOSE',title:'One order. Keep it close.',lead:'Keep bags from the same order together whenever you can.',why:"If there is enough space, don't split one order between different shelves or areas.",rule1:'Write the order number on every bag.',rule2:'If there is room, place the bags from one order next to each other.',fridgeFull:'FRIDGE FULL?',coldBag:'COLD BAG',fridge:'FRIDGE',restOrder:'REST OF THE SAME ORDER',crate:'DESIGNATED CRATE BELOW / IN FRONT OF THAT FRIDGE',exception:'This is an exception for lack of fridge space, not the normal way to split orders.'},
      done:{step:'06 / FINISH THE JOB',packed:'PACKED',done:'DONE',numbered:'NUMBERED',stored:'STORED',lead:'Packing the bags is not the end of the job. Finished orders need to reach the fridge or the correct shelf.',minimumLabel:'When it is very busy:',minimum:"At least bring the finished cart to the fridge area. Do not leave it on the other side of the checker.",help:'If nobody is organizing the bags and you have a moment, help put them away.'},
      carts:{step:'07 / CARTS',title:'This is not cart parking.',lead:'Empty carts pile up very quickly during peak hours. If you see this happening, move them.',empty:'EMPTY CARTS',destination:'B1-B9',clear:'Move them to B1-B9 near the bread shelves. Keep the checker clear.'},
      water:{step:'08 / WATER MULTIPACKS',title:'Water goes in a bag.',lead:'Couriers often grab the paper bags and forget loose water behind.',rule:'Put the water multipack inside a Wolt bag and close it normally.'},
      diapers:{step:'DIAPERS',title:'Diapers go in a bag.',lead:"A sticker doesn't turn it into a bag. Put diaper packs inside a Wolt bag."},
      listen:{step:'09 / STAY AWARE',title:'Hear a number? Look around.',call:'"SEVEN FOUR FOUR?"',lead:'When a shift manager calls a number, check the bags around you. If you see it, say so.',why:'A quick answer can save several minutes of searching.'},
      checklist:{step:'10 / THE FINAL CHECK',title:'Before you walk away.',items:['Correct order number','Number and customer name on every bag','Big and readable','Side facing outward','Order bags together or in the designated crate','Correct shelf or fridge','Finished cart is not abandoned','Empty carts do not block the checker'],closing:"MAKE THE NEXT PERSON'S JOB EASIER.",done:'DONE ✓'}
    },
    knowledge:{step:'FINAL / KNOWLEDGE CHECK',title:'Ready for peak hours?',intro:'Quick situations covering the whole guide. About 2–3 minutes.',question:'QUESTION {current} / {total}',score:'{score} correct',continue:'CONTINUE →',result:'SEE RESULT →',correct:'Correct.',incorrect:'Not quite.',ready:'READY FOR PEAK HOURS ✓',almost:'ALMOST THERE',reviewGuide:'REVIEW THE GUIDE',review:'Review these:',perfect:'12/12. Okay, show-off. You actually read the whole thing.',fromQuiz:'From your quiz',backResults:'← BACK TO QUIZ RESULTS',reviewLinkLabel:'Review rule: {title}',questions:[
      {q:'A cart reaches the packing area, but one item is missing. What should you do?',a:['Start packing anyway.','Move it aside until the whole order is ready.','Add the item after packing starts.'],correct:1,rule:'A cart enters the packing area only when the entire order is ready.',label:'Ready means ready'},
      {q:'The app shows 726 and you think you remember it. What should you write?',a:['Check the app again and write 726.','Write 762 from memory.','Any version with those digits.'],correct:0,rule:'Check the app before writing. 726 is not 762, 267, 276, 627 or 672.',label:'Check the number'},
      {q:'You can read your handwriting, but another coworker cannot. Is it okay?',a:['Yes, because you know the number.','Only during quiet hours.','No. Another person must read it immediately.'],correct:2,rule:'Write the number clearly enough for another person to read.',label:'Write clearly'},
      {q:'The fridge is crowded. How should you write the number?',a:['On the folded side in small writing.','Open the side, write it big, and place it lower if that helps visibility.','Only on the top sticker.'],correct:1,rule:'Flatten the side and write the number big. Lower on the side is fine when it is easier to see.',label:'Make the number visible'},
      {q:"The bag says 'Shabbat Shalom' but has no customer name. Is it finished?",a:['Yes, the greeting is enough.','Only if the order number is clear.','No. Copy the customer name from the app.'],correct:2,rule:"A greeting does not replace the customer's actual name.",label:'Write the customer name'},
      {q:'There is enough space for all three bags of one order. Where should they go?',a:['Together or directly next to each other.','On different shelves.','Wherever there is a gap.'],correct:0,rule:'Keep bags from one order close whenever possible.',label:'Keep the order close'},
      {q:'The fridge is full and one bag needs refrigeration. Where do the other bags go?',a:['Anywhere outside the fridge.','At the checker.','In the designated crate below or in front of that fridge.'],correct:2,rule:'The cold bag stays inside; the rest use the designated crate by that fridge.',label:'Fridge-full exception'},
      {q:'The bags are packed but have not been numbered or stored. Is the order done?',a:['No. It must be numbered and placed correctly.','Yes, packing is the last step.','Yes, if the cart is full.'],correct:0,rule:'Packed does not mean done. Number and store the finished order.',label:'Finish the order'},
      {q:'Empty carts are blocking the checker. Where do they go?',a:['Next to the fridge.','B1-B9 near the bread shelves.','Anywhere outside the packing area.'],correct:1,rule:'Move empty carts to B1-B9 and keep the checker clear.',label:'Empty carts to B1-B9'},
      {q:'An order includes a water multipack. How should it be packed?',a:['Leave it loose beside the bags.','Put it inside a Wolt bag.','Hand it separately to the courier.'],correct:1,rule:'Water multipacks go inside a Wolt bag so they are not left behind.',label:'Water goes in a bag'},
      {q:'A diaper pack has a Wolt sticker and order number on it. Is that enough?',a:['Yes, the sticker turns it into a bag.','Only for large diaper packs.','No. Put it inside a Wolt bag.'],correct:2,rule:'A sticker is not a bag. Diaper packs go inside a Wolt bag.',label:'Diapers go in a bag'},
      {q:'The shift manager calls an order number and you can see that order. What should you do?',a:['Say that you see it.','Stay quiet unless asked twice.','Move it without saying anything.'],correct:0,rule:'A quick answer can save the team several minutes of searching.',label:'Listen and help'}
    ]}
  },
  he: {
    meta:{name:'עברית',choose:'בחרו שפה',switch:'שפה',brand:'שעות עומס'},
    signature:'נעשה באהבה ועם קצת טראומה ממשמרות עומס. אלינה',
    hero:{duration:'מדריך של 3 דקות',kicker:'מדריך קצר לצוות',peak:'שעות',hours:'עומס.',intro:'כמה שניות עכשיו יכולות לחסוך כמה דקות בצ׳קר.',rule:'להקל על מי שעובד אחריכם.',start:'מתחילים'},
    introduction:{heading:'בשעות עומס נהיה בלגן מהר.',p1:'כשעשרות הזמנות מוכנות ושליחים מחכים בצ׳קר, כל דבר קטן משפיע.',p2:'במדריך הזה יש כמה כללים פשוטים שעוזרים לארוז, למצוא ולמסור הזמנות.',p3:'רובם לוקחים כמה שניות וחוסכים לכולם הרבה יותר זמן אחר כך.',goalLabel:'המטרה פשוטה:',goal:'להקל על מי שעובד אחריכם.'},
    labels:{before:'לפני',after:'אחרי',wrong:'× לא נכון',right:'✓ נכון'},
    photos:{folded:'צד השקית עדיין מקופל.',flat:'צד השקית פתוח ושטוח.',separate:'שקיות מאותה הזמנה פוזרו בלי סיבה.',together:'שקיות מאותה הזמנה נשמרות קרוב.',finishedCarts:'הזמנות מוכנות נשארו על עגלות ליד הצ׳קר.',carts:'עגלות ריקות חוסמות את הצ׳קר.',waterLoose:'מארז מים נשאר מחוץ לשקיות ההזמנה.',waterBag:'מארז מים נמצא בתוך שקית וולט.',numberStyles:'דוגמה לסגנונות שונים וברורים של ספרות בכתב יד.',handwriting939:'תווית אמיתית על שקית עם מספר ההזמנה 939 בכתב יד.',customerNameBefore:'על השקית יש ברכה, אבל אין שם לקוח.',customerNameAfter:'על אותה שקית כתוב בבירור השם Daniel.',diaperWrong:'חבילת חיתולים משמשת כפריט נפרד עם מדבקת וולט.',diaperRight:'חבילת חיתולים נמצאת בתוך שקית נייר של וולט.'},
    sections:{
      ready:{step:'01 / מוכן זה מוכן',title:'אם זה כאן, זה מוכן.',equation:'אזור אריזה = מוכן לאריזה',cart:'עגלה',area:'אזור אריזה',ready:'מוכן לאריזה',notReady:'עדיין לא מוכן',flowLabel:'עגלה אל אזור האריזה ומשם למוכן לאריזה',lead:'מי שאורז צריך להתחיל מיד.',noteTitle:'עדיין חסר משהו?',note:'עדכנו את מי שאורז והשאירו את העגלה מחוץ לאזור האריזה עד שהכול מוכן. אל תוסיפו מוצרים אחרי שהאריזה התחילה.'},
      number:{step:'02 / בודקים את המספר',title:'בודקים. ואז בודקים שוב.',lead:'בדקו את המספר לפני שאתם כותבים. אחרי עשרות הזמנות קל מאוד להחליף בין הספרות.',app:'באפליקציה',not:'לא',why:'אם באפליקציה כתוב 726, רק 726 נכון.'},
      writing:{step:'03 / כותבים ברור',title:'מישהו אחר יכול לקרוא את זה?',lead:'אנשים כותבים מספרים בצורות שונות וזה בסדר. מה שחשוב הוא שמישהו אחר יוכל לקרוא את המספר מיד.',question:'איזה מספר זה?',choose:'בחרו תשובה:',answers:['435','439','939','935','545','539'],feedback:['כן... לגמרי אפשר להבין את הניחוש. אבל זה 939.','כן... לגמרי אפשר להבין את הניחוש. אבל זה 939.','וואו. אתם קוראים מחשבות? זה באמת 939. אבל לא אמורים לנחש.','כן... לגמרי אפשר להבין את הניחוש. אבל זה 939.','כן... לגמרי אפשר להבין את הניחוש. אבל זה 939.','כן... לגמרי אפשר להבין את הניחוש. אבל זה 939.']},
      visible:{step:'04 / הופכים את המספר לגלוי',title:'קודם משטחים את הצד.',lead:'לפני שכותבים את המספר, פותחים את צד השקית ומשטחים אותו.',rule:'אחר כך כותבים את מספר ההזמנה בגדול. צריך לראות אותו בלי להזיז את השקית.',tip:'אם המקרר עמוס, אפשר לכתוב את המספר נמוך יותר בצד השקית כדי שיהיה קל יותר לראות אותו.'},
      customerName:{step:'שם הלקוח',title:'ברכה יפה. אבל למי?',lead:'תמיד כותבים את שם הלקוח על השקית.',detail:'מעתיקים את השם מהאפליקציה. ״שבת שלום״ או ברכה אחרת לא מחליפים את שם הלקוח.',playful:'שבת שלום זה מקסים. אבל למי השקית?'},
      together:{step:'05 / שומרים קרוב',title:'הזמנה אחת. שומרים קרוב.',lead:'ככל שאפשר, שומרים את השקיות של אותה הזמנה יחד.',why:'אם יש מקום, לא מפזרים הזמנה אחת בין מדפים או אזורים שונים.',rule1:'כותבים את מספר ההזמנה על כל שקית.',rule2:'אם יש מקום, מניחים את שקיות ההזמנה זו ליד זו.',fridgeFull:'המקרר מלא?',coldBag:'שקית שצריכה קירור',fridge:'מקרר',restOrder:'שאר השקיות של אותה הזמנה',crate:'ארגז מתקפל ייעודי מתחת למקרר הזה או מולו',exception:'זה פתרון רק כשאין מקום במקרר, לא הדרך הרגילה לפצל הזמנה.'},
      done:{step:'06 / מסיימים את העבודה',packed:'ארוז',done:'מוכן',numbered:'ממוספר',stored:'במקום',lead:'אריזת השקיות היא לא סוף העבודה. הזמנות מוכנות צריכות להגיע למקרר או למדף הנכון.',minimumLabel:'כשעמוס מאוד:',minimum:'לפחות הביאו את העגלה המוכנה לאזור המקררים. אל תשאירו אותה בצד השני של הצ׳קר.',help:'אם אף אחד לא מסדר את השקיות ויש לכם רגע, עזרו להכניס אותן למקום.'},
      carts:{step:'07 / עגלות',title:'זה לא חניון עגלות.',lead:'עגלות ריקות מצטברות מהר מאוד בשעות עומס. אם זה מתחיל לקרות, מזיזים אותן.',empty:'עגלות ריקות',destination:'B1-B9',clear:'מעבירים ל-B1-B9 ליד מדפי הלחם. משאירים את הצ׳קר פנוי.'},
      water:{step:'08 / מארזי מים',title:'מים נכנסים לשקית.',lead:'שליחים לוקחים את שקיות הנייר ולפעמים שוכחים את מארז המים שנשאר בחוץ.',rule:'מכניסים את מארז המים לשקית וולט וסוגרים אותה כרגיל.'},
      diapers:{step:'חיתולים',title:'חיתולים נכנסים לשקית.',lead:'מדבקה לא הופכת חבילת חיתולים לשקית. מכניסים אותה לשקית וולט רגילה.'},
      listen:{step:'09 / נשארים קשובים',title:'שמעתם מספר? תסתכלו מסביב.',call:'״שבע ארבע ארבע?״',lead:'כשאחמ״ש קורא מספר, בדקו את השקיות לידכם. אם מצאתם, תגידו.',why:'תשובה מהירה יכולה לחסוך כמה דקות של חיפוש.'},
      checklist:{step:'10 / בדיקה אחרונה',title:'לפני שממשיכים הלאה.',items:['מספר הזמנה נכון','מספר ושם לקוח על כל שקית','גדול וברור','הצד פונה החוצה','שקיות ההזמנה יחד או בארגז הייעודי','מדף או מקרר נכון','עגלה מוכנה לא ננטשה','עגלות ריקות לא חוסמות את הצ׳קר'],closing:'להקל על מי שעובד אחריכם.',done:'סיימנו ✓'}
    },
    knowledge:{step:'סיום / בדיקת ידע',title:'מוכנים לשעות עומס?',intro:'מצבים קצרים מכל המדריך. בערך 2–3 דקות.',question:'שאלה {current}/{total}',score:'{score}/{total}',continue:'המשך ←',result:'לתוצאה ←',correct:'נכון.',incorrect:'לא בדיוק.',ready:'מוכנים לשעות עומס ✓',almost:'כמעט שם',reviewGuide:'כדאי לחזור על המדריך',review:'כדאי לעבור שוב על:',perfect:'12/12. טוב, אפשר להשוויץ. באמת קראתם הכול.',fromQuiz:'מהקוויז שלכם',backResults:'חזרה לתוצאות הקוויז →',reviewLinkLabel:'חזרה על הכלל: {title}',questions:[
      {q:'עגלה הגיעה לאזור האריזה אבל חסר מוצר. מה עושים?',a:['מתחילים לארוז.','מזיזים הצידה עד שכל ההזמנה מוכנה.','מוסיפים את המוצר אחרי שמתחילים.'],correct:1,rule:'עגלה נכנסת לאזור האריזה רק כשההזמנה כולה מוכנה.',label:'מוכן זה מוכן'},
      {q:'באפליקציה כתוב 726 ונראה לכם שאתם זוכרים. מה כותבים?',a:['בודקים שוב וכותבים 726.','כותבים 762 מהזיכרון.','כל סדר של אותן ספרות.'],correct:0,rule:'בודקים באפליקציה. 726 הוא לא 762, 267, 276, 627 או 672.',label:'בודקים את המספר'},
      {q:'אתם קוראים את כתב היד שלכם אבל מישהו אחר לא. זה בסדר?',a:['כן, כי אתם יודעים את המספר.','רק כשלא עמוס.','לא. מישהו אחר צריך לקרוא אותו מיד.'],correct:2,rule:'כותבים את המספר ברור כדי שמישהו אחר יקרא אותו מיד.',label:'כותבים ברור'},
      {q:'המקרר צפוף. איך כותבים את המספר?',a:['קטן על צד מקופל.','פותחים את הצד, כותבים בגדול ונמוך יותר אם זה עוזר.','רק על המדבקה למעלה.'],correct:1,rule:'משטחים את הצד וכותבים בגדול. אפשר נמוך יותר אם כך רואים טוב יותר.',label:'המספר צריך להיות גלוי'},
      {q:'על השקית כתוב ״שבת שלום״ אבל אין שם לקוח. היא מוכנה?',a:['כן, הברכה מספיקה.','רק אם המספר ברור.','לא. מעתיקים את שם הלקוח מהאפליקציה.'],correct:2,rule:'ברכה לא מחליפה את השם האמיתי של הלקוח.',label:'כותבים שם לקוח'},
      {q:'יש מספיק מקום לשלוש שקיות של אותה הזמנה. איפה מניחים?',a:['זו ליד זו.','במדפים שונים.','בכל מקום פנוי.'],correct:0,rule:'ככל שאפשר, שומרים את שקיות ההזמנה קרוב.',label:'שומרים קרוב'},
      {q:'המקרר מלא ושקית אחת צריכה קירור. איפה שאר השקיות?',a:['בכל מקום מחוץ למקרר.','בצ׳קר.','בארגז הייעודי מתחת למקרר הזה או מולו.'],correct:2,rule:'השקית הקרה בפנים והשאר בארגז הייעודי ליד אותו מקרר.',label:'חריג כשהמקרר מלא'},
      {q:'השקיות ארוזות אבל אין עליהן מספר והן לא במקום. ההזמנה מוכנה?',a:['לא. צריך לכתוב מספר ולהניח במקום הנכון.','כן, האריזה היא השלב האחרון.','כן, אם העגלה מלאה.'],correct:0,rule:'ארוז לא אומר מוכן. כותבים מספר ומניחים את ההזמנה במקום.',label:'מסיימים את העבודה'},
      {q:'עגלות ריקות חוסמות את הצ׳קר. לאן מעבירים?',a:['ליד המקרר.','ל-B1-B9 ליד מדפי הלחם.','לכל מקום מחוץ לאזור האריזה.'],correct:1,rule:'מעבירים עגלות ריקות ל-B1-B9 ומשאירים את הצ׳קר פנוי.',label:'עגלות ל-B1-B9'},
      {q:'בהזמנה יש מארז מים. איך אורזים?',a:['משאירים ליד השקיות.','מכניסים לשקית וולט.','מוסרים בנפרד לשליח.'],correct:1,rule:'מארזי מים נכנסים לשקית וולט כדי שלא יישארו מאחור.',label:'מים בתוך שקית'},
      {q:'על חבילת חיתולים יש מדבקת וולט ומספר. זה מספיק?',a:['כן, המדבקה הופכת אותה לשקית.','רק לחבילות גדולות.','לא. מכניסים אותה לשקית וולט.'],correct:2,rule:'מדבקה היא לא שקית. חיתולים נכנסים לשקית וולט.',label:'חיתולים בשקית'},
      {q:'אחמ״ש קורא מספר הזמנה ואתם רואים אותה. מה עושים?',a:['אומרים שרואים אותה.','שותקים עד ששואלים שוב.','מזיזים אותה בלי לומר דבר.'],correct:0,rule:'תשובה מהירה יכולה לחסוך לצוות כמה דקות חיפוש.',label:'מקשיבים ועוזרים'}
    ]}
  },
  th: {
    meta:{name:'ไทย',choose:'เลือกภาษา',switch:'ภาษา',brand:'ช่วงเวลาเร่งด่วน'},
    signature:'ทำด้วยความรักและความหลอนนิด ๆ จากช่วงพีก อลีนา',
    hero:{duration:'คู่มือ 3 นาที',kicker:'คู่มือสั้นสำหรับทีม',peak:'ช่วงเวลา',hours:'เร่งด่วน',intro:'ใช้เวลาไม่กี่วินาทีตอนนี้ ช่วยประหยัดเวลาหลายนาทีที่จุดเช็กเกอร์ได้',rule:'ช่วยให้งานของคนถัดไปง่ายขึ้น',start:'เริ่มคู่มือ'},
    introduction:{heading:'ช่วงเร่งด่วนวุ่นวายได้เร็วมาก',p1:'พอมีออเดอร์เสร็จพร้อมกันหลายสิบออเดอร์และไรเดอร์ต่อแถวที่จุดเช็กเกอร์ เรื่องเล็ก ๆ ก็มีผลมาก',p2:'คู่มือนี้มีกฎง่าย ๆ ไม่กี่ข้อ ช่วยให้แพ็ก หา และส่งออเดอร์ได้ง่ายขึ้น',p3:'แต่ละข้อใช้เวลาแค่ไม่กี่วินาที แต่ช่วยประหยัดเวลาให้ทุกคนได้มากในภายหลัง',goalLabel:'เป้าหมายง่าย ๆ คือ',goal:'ช่วยให้งานของคนถัดไปง่ายขึ้น'},
    labels:{before:'ก่อน',after:'หลัง',wrong:'× ผิด',right:'✓ ถูก'},
    photos:{folded:'ด้านข้างของถุงยังพับอยู่',flat:'ด้านข้างของถุงเปิดและแบนแล้ว',separate:'ถุงของออเดอร์เดียวกันถูกแยกไว้คนละที่โดยไม่จำเป็น',together:'ถุงของออเดอร์เดียวกันอยู่ใกล้กัน',finishedCarts:'ออเดอร์ที่เสร็จแล้วถูกทิ้งไว้บนรถเข็นรอบจุดเช็กเกอร์',carts:'รถเข็นเปล่าขวางจุดเช็กเกอร์',waterLoose:'แพ็กน้ำอยู่นอกถุงออเดอร์',waterBag:'แพ็กน้ำอยู่ในถุง Wolt',numberStyles:'ตัวอย่างรูปแบบตัวเลขลายมือที่แตกต่างกันและอ่านได้',handwriting939:'ป้ายบนถุงจริงที่เขียนหมายเลขออเดอร์ 939 ด้วยลายมือ',customerNameBefore:'บนถุงมีคำอวยพร แต่ไม่มีชื่อลูกค้า',customerNameAfter:'ถุงใบเดิมที่เขียนชื่อ Daniel ไว้ชัดเจน',diaperWrong:'แพ็กผ้าอ้อมถูกใช้เป็นของแยกโดยติดสติกเกอร์ Wolt',diaperRight:'แพ็กผ้าอ้อมอยู่ภายในถุงกระดาษ Wolt'},
    sections:{
      ready:{step:'01 / พร้อมคือพร้อม',title:'ถ้าอยู่ตรงนี้ ต้องพร้อมแพ็ก',equation:'พื้นที่แพ็ก = พร้อมแพ็ก',cart:'รถเข็น',area:'พื้นที่แพ็ก',ready:'พร้อมแพ็ก',notReady:'ยังไม่พร้อม',flowLabel:'รถเข็นไปพื้นที่แพ็กแล้วพร้อมแพ็ก',lead:'คนแพ็กต้องเริ่มงานได้ทันที',noteTitle:'ยังขาดของอยู่หรือไม่?',note:'บอกคนแพ็กและเก็บรถเข็นไว้นอกพื้นที่แพ็กจนกว่าออเดอร์จะพร้อม อย่าเติมของหลังจากเริ่มแพ็กแล้ว'},
      number:{step:'02 / ตรวจเลขออเดอร์',title:'เช็กแล้วเช็กอีกที',lead:'เช็กเลขก่อนเขียน พอเจอออเดอร์เยอะ ๆ ตัวเลขสลับกันได้ง่ายมาก',app:'ในแอป',not:'ไม่ใช่',why:'ถ้าในแอปเขียน 726 เลขที่ถูกต้องก็มีแค่ 726'},
      writing:{step:'03 / เขียนให้อ่านง่าย',title:'คนอื่นอ่านออกไหม?',lead:'แต่ละคนเขียนตัวเลขไม่เหมือนกัน ไม่เป็นไร สิ่งสำคัญคือคนอื่นต้องอ่านของคุณออกทันที',question:'นี่คือเลขอะไร?',choose:'เลือกคำตอบ:',answers:['435','439','939','935','545','539'],feedback:['ใช่... เดาแบบนั้นก็เข้าใจได้ แต่จริง ๆ คือ 939','ใช่... เดาแบบนั้นก็เข้าใจได้ แต่จริง ๆ คือ 939','โอ้โห อ่านใจได้หรือเปล่า? มันคือ 939 จริง ๆ แต่เราไม่ควรต้องเดา','ใช่... เดาแบบนั้นก็เข้าใจได้ แต่จริง ๆ คือ 939','ใช่... เดาแบบนั้นก็เข้าใจได้ แต่จริง ๆ คือ 939','ใช่... เดาแบบนั้นก็เข้าใจได้ แต่จริง ๆ คือ 939']},
      visible:{step:'04 / ทำให้มองเห็น',title:'คลี่ด้านข้างก่อน',lead:'ก่อนเขียนเลข ให้เปิดด้านข้างของถุงและคลี่ให้แบน',rule:'จากนั้นเขียนเลขออเดอร์ให้ใหญ่ ต้องมองเห็นได้โดยไม่ต้องขยับถุง',tip:'ถ้าตู้เย็นแน่น เขียนเลขให้ต่ำลงตรงด้านข้างถุงได้ จะมองเห็นง่ายขึ้น'},
      customerName:{step:'ชื่อลูกค้า',title:'ข้อความน่ารัก แล้วเขียนให้ใครล่ะ?',lead:'เขียนชื่อลูกค้าจริงบนถุงทุกใบ',detail:'คัดลอกชื่อจากแอป “Shabbat Shalom” หรือคำอวยพรอื่นใช้แทนชื่อลูกค้าไม่ได้',playful:'Shabbat Shalom ก็น่ารักนะ แต่ถุงนี้ของใครล่ะ?'},
      together:{step:'05 / เก็บไว้ใกล้กัน',title:'หนึ่งออเดอร์ เก็บไว้ใกล้กัน',lead:'เก็บถุงของออเดอร์เดียวกันไว้ด้วยกันเท่าที่ทำได้',why:'ถ้ามีที่พอ อย่าแยกออเดอร์เดียวไปคนละชั้นหรือคนละโซนโดยไม่จำเป็น',rule1:'เขียนเลขออเดอร์บนทุกถุง',rule2:'ถ้ามีที่ ให้วางถุงของออเดอร์เดียวกันไว้ติดกัน',fridgeFull:'ตู้เย็นเต็ม?',coldBag:'ถุงที่ต้องแช่เย็น',fridge:'ตู้เย็น',restOrder:'ถุงที่เหลือของออเดอร์เดียวกัน',crate:'ลังพับที่กำหนดไว้ตรงใต้หรือหน้าตู้เย็นตู้นั้น',exception:'ใช้วิธีนี้เฉพาะตอนตู้เย็นไม่มีที่ ไม่ใช่วิธีปกติในการแยกออเดอร์'},
      done:{step:'06 / ทำงานให้เสร็จ',packed:'แพ็กแล้ว',done:'เสร็จ',numbered:'มีเลขแล้ว',stored:'เก็บแล้ว',lead:'แพ็กถุงเสร็จยังไม่ใช่จบงาน ออเดอร์ที่เสร็จต้องไปที่ตู้เย็นหรือชั้นที่ถูกต้อง',minimumLabel:'ตอนยุ่งมาก:',minimum:'อย่างน้อยให้เข็นออเดอร์ที่เสร็จแล้วไปไว้แถวตู้เย็น อย่าทิ้งไว้ฝั่งอื่นของจุดเช็กเกอร์',help:'ถ้าไม่มีใครกำลังจัดถุงและพอมีเวลา ช่วยนำถุงไปเก็บเข้าที่'},
      carts:{step:'07 / รถเข็น',title:'ตรงนี้ไม่ใช่ที่จอดรถเข็น',lead:'รถเข็นเปล่าสะสมเร็วมากในช่วงเร่งด่วน ถ้าเห็นว่าเริ่มกอง ให้ย้ายออก',empty:'รถเข็นเปล่า',destination:'B1-B9',clear:'ย้ายไป B1-B9 ใกล้ชั้นขนมปัง รักษาพื้นที่เช็กเกอร์ให้โล่ง'},
      water:{step:'08 / แพ็กน้ำ',title:'น้ำต้องใส่ถุง',lead:'ไรเดอร์มักหยิบถุงกระดาษและลืมน้ำที่วางแยกไว้',rule:'ใส่แพ็กน้ำในถุง Wolt แล้วปิดถุงตามปกติ'},
      diapers:{step:'ผ้าอ้อม',title:'ผ้าอ้อมต้องใส่ถุง',lead:'แค่ติดสติกเกอร์ก็ยังไม่กลายเป็นถุง ต้องใส่แพ็กผ้าอ้อมไว้ในถุง Wolt'},
      listen:{step:'09 / คอยฟังรอบตัว',title:'ได้ยินเลขไหม? มองรอบตัว',call:'“เจ็ด สี่ สี่?”',lead:'ถ้าหัวหน้ากะเรียกเลขออเดอร์ ให้ดูถุงรอบตัว ถ้าเจอให้บอกทันที',why:'ตอบสั้น ๆ แค่นี้ก็ช่วยประหยัดเวลาหาได้หลายนาที'},
      checklist:{step:'10 / ตรวจครั้งสุดท้าย',title:'ก่อนเดินออกไป',items:['เลขออเดอร์ถูกต้อง','มีเลขและชื่อลูกค้าบนทุกถุง','ใหญ่และอ่านง่าย','ด้านข้างหันออก','ถุงอยู่ด้วยกันหรือในลังที่กำหนด','ชั้นหรือตู้เย็นถูกต้อง','ไม่ทิ้งรถเข็นที่เสร็จแล้ว','รถเข็นเปล่าไม่ขวางจุดเช็กเกอร์'],closing:'ช่วยให้งานของคนถัดไปง่ายขึ้น',done:'เสร็จ ✓'}
    },
    knowledge:{step:'สุดท้าย / ทบทวนความเข้าใจ',title:'พร้อมสำหรับช่วงเร่งด่วนไหม?',intro:'สถานการณ์สั้น ๆ ครบทั้งคู่มือ ใช้เวลาประมาณ 2–3 นาที',question:'คำถาม {current} / {total}',score:'ถูก {score} ข้อ',continue:'ต่อไป →',result:'ดูผล →',correct:'ถูกต้อง',incorrect:'ยังไม่ถูก',ready:'พร้อมสำหรับช่วงเร่งด่วน ✓',almost:'เกือบพร้อมแล้ว',reviewGuide:'กลับไปทบทวนคู่มือ',review:'ทบทวนหัวข้อเหล่านี้:',perfect:'12/12 โอเค เก่งเกิน จะอวดก็อวดเลย อ่านครบจริง ๆ ด้วยสินะ',fromQuiz:'จากผลควิซของคุณ',backResults:'← กลับไปดูผลควิซ',reviewLinkLabel:'ทบทวนกฎ: {title}',questions:[
      {q:'รถเข็นเข้าพื้นที่แพ็ก แต่ยังขาดสินค้าหนึ่งชิ้น ควรทำอย่างไร?',a:['เริ่มแพ็กก่อนได้','ย้ายออกจนกว่าออเดอร์จะครบ','เติมของทีหลัง'],correct:1,rule:'พร้อมแพ็กหมายถึงทั้งออเดอร์พร้อมก่อนเริ่มแพ็ก',label:'พร้อมคือพร้อม'},
      {q:'ในแอปเขียน 726 ควรเขียนเลขไหนบนถุง?',a:['เช็กอีกครั้งแล้วเขียน 726','เขียน 762 จากความจำ','เขียนเลขไหนก็ได้ที่ใกล้เคียง'],correct:0,rule:'เช็กเลขในแอปก่อนเขียนทุกครั้ง อย่าเขียนจากความจำ',label:'ตรวจเลขออเดอร์'},
      {q:'เราอ่านเลขบนถุงออก แต่คนอื่นต้องเดา แบบนี้ได้ไหม?',a:['ได้ ถ้าเราอ่านออก','ได้เฉพาะตอนร้านเงียบ','ไม่ได้ คนอื่นต้องอ่านออกทันที'],correct:2,rule:'เขียนตัวเลขให้ใหญ่และชัดจนคนอื่นอ่านออกทันที',label:'เขียนให้อ่านง่าย'},
      {q:'ตู้เย็นแน่นมาก ควรเขียนเลขบนถุงอย่างไร?',a:['เขียนเล็ก ๆ บนรอยพับ','คลี่ด้านข้าง เขียนใหญ่ และเขียนต่ำลงได้','ใช้แค่สติกเกอร์ด้านบน'],correct:1,rule:'ทำด้านข้างให้แบนและให้เลขมองเห็นได้โดยไม่ต้องขยับถุง',label:'ทำให้มองเห็น'},
      {q:'เขียนคำอวยพรบนถุงแล้ว แต่ไม่มีชื่อลูกค้า พอไหม?',a:['พอแล้ว','พอถ้าเลขชัด','ไม่พอ ต้องคัดลอกชื่อลูกค้าจากแอป'],correct:2,rule:'ทุกถุงต้องมีทั้งเลขออเดอร์และชื่อลูกค้า',label:'เขียนชื่อลูกค้า'},
      {q:'ออเดอร์หนึ่งมีสามถุงและมีที่พอ ควรวางอย่างไร?',a:['วางติดกัน','แยกคนละชั้น','วางช่องไหนก็ได้'],correct:0,rule:'เก็บถุงของออเดอร์เดียวกันไว้ด้วยกันเมื่อทำได้',label:'เก็บออเดอร์ไว้ใกล้กัน'},
      {q:'ตู้เย็นเต็มและมีหนึ่งถุงที่ต้องแช่เย็น แล้วถุงที่เหลือไว้ไหน?',a:['วางตรงไหนก็ได้','ทิ้งไว้ที่เช็กเกอร์','ใส่ลังที่กำหนดตรงใต้หรือหน้าตู้เย็นตู้นั้น'],correct:2,rule:'ถุงที่ต้องแช่เย็นอยู่ในตู้เย็น ส่วนถุงที่เหลืออยู่ในลังที่กำหนดตรงใต้หรือหน้าตู้เย็นตู้นั้น',label:'ข้อยกเว้นเมื่อตู้เย็นเต็ม'},
      {q:'แพ็กเสร็จแล้วแต่ยังไม่ได้เขียนเลขหรือเก็บเข้าที่ ถือว่าเสร็จไหม?',a:['ยังไม่เสร็จ','เสร็จแล้ว','เสร็จถ้ารถเข็นเต็ม'],correct:0,rule:'งานเสร็จเมื่อแพ็ก เขียนเลข และเก็บไว้ในจุดที่ถูกต้องแล้ว',label:'ทำงานให้เสร็จ'},
      {q:'รถเข็นเปล่าควรย้ายไปไหน?',a:['ข้างตู้เย็น','B1-B9 ใกล้ชั้นขนมปัง','ตรงไหนก็ได้'],correct:1,rule:'ย้ายรถเข็นเปล่าไป B1-B9 และรักษาจุดเช็กเกอร์ให้โล่ง',label:'รถเข็นไป B1-B9'},
      {q:'ออเดอร์มีแพ็กน้ำ ควรทำอย่างไร?',a:['วางแยกข้างถุง','ใส่ในถุง Wolt แล้วปิด','ส่งให้ไรเดอร์แยกต่างหาก'],correct:1,rule:'แพ็กน้ำต้องอยู่ในถุง Wolt เพื่อไม่ให้ถูกลืม',label:'น้ำต้องใส่ถุง'},
      {q:'แพ็กผ้าอ้อมติดสติกเกอร์ Wolt แล้ว ถือว่าแพ็กเสร็จไหม?',a:['เสร็จแล้ว','เสร็จเฉพาะแพ็กใหญ่','ยัง ต้องใส่ในถุง Wolt'],correct:2,rule:'สติกเกอร์ไม่ใช่ถุง แพ็กผ้าอ้อมต้องอยู่ในถุง Wolt',label:'ผ้าอ้อมต้องใส่ถุง'},
      {q:'หัวหน้ากะเรียกเลขออเดอร์และเราเห็นถุงนั้น ควรทำยังไง?',a:['บอกทันทีว่าเจอแล้ว','เงียบไว้','ย้ายถุงโดยไม่พูด'],correct:0,rule:'ถ้าเห็นออเดอร์ที่ถูกเรียก ให้ตอบทันที จะได้ไม่เสียเวลาหา',label:'คอยฟังรอบตัว'}
    ]}
  }
};

const quizSectionIds = [
  'ready-to-pack',
  'check-number',
  'write-clearly',
  'number-visible',
  'customer-name',
  'keep-order-together',
  'fridge-full',
  'finished-order',
  'carts',
  'water',
  'diapers',
  'listen-help'
];

Object.values(window.translations).forEach((language) => {
  language.knowledge.questions.forEach((question, index) => {
    question.relatedSection = quizSectionIds[index];
  });
});
